// import modules
import React from "react";
import { useNavigate } from "react-router-dom";

// define component
const Terms = () => {
    // declare the state variable
    const navigate = useNavigate();

    // handle back button click event
    const handleBack = () => {
        // navigate to home page
        navigate("/");
    }

    return (
        <div className="container mx-3 d-flex flex-column justify-content-center align-items-center">
            <div className="d-flex align-items-center justify-content-around w-100 bg-dark border border-dark rounded-3">
                <h1>&#128151;</h1>
                <h1 className="text-info fs-1 py-2">Love Calculator</h1>
                <h1>&#128151;</h1>
            </div>
            <div className="d-flex flex-column text-justify border border-secondary rounded-3 bg-dark w-100">
                <h2 className="text-light fs-4 py-2">Terms and Conditions</h2>
                <p className="text-light text-justify fs-6 px-3">
                    Welcome to the Love Calculator App! Before you start using our service, we kindly ask you to carefully read and understand the following Terms and Conditions. By accessing or using our Love Calculator App, you agree to be bound by these Terms and Conditions.
                    <ol>
                        <li>Acceptance of Terms
                            <p> By accessing or using the Love Calculator App, you agree to comply with and be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the app.</p>
                        </li>
                        <li>Use of the Love Calculator
                            <p>The Love Calculator App provides a service that calculates compatibility between couples based on their date of birth. It's important to note that the results generated by the Love Calculator are intended for entertainment purposes only and should not be considered as professional relationship advice.</p>
                        </li>
                        <li>Privacy Protection
                            <p>We are committed to protecting your privacy and maintaining the security of your personal information. When using the Love Calculator App, we may collect certain data, including names and dates of birth. This data is used solely for the purpose of calculating compatibility and generating results. We do not share this data with any third parties.</p>
                        </li>
                        <li>Data Security
                            <p> We take appropriate technical and organizational measures to ensure the security of the data you provide. However, please be aware that no method of data transmission over the internet or electronic storage is 100% secure. While we strive to protect your personal information, we cannot guarantee its absolute security.</p>
                        </li>
                        <li>User Responsibilities
                            <p>You agree not to use the Love Calculator App for any unlawful or unauthorized purpose.</p>
                            <p>You agree not to attempt to access, interfere with, or disrupt the Love Calculator App's services, servers, or networks.</p>
                            <p>You agree not to use the Love Calculator App to collect, store, or disclose personal data of other users without their consent.</p>
                        </li>
                        <li>Limitation of Liability
                            <p>The Love Calculator App and its creators shall not be liable for any direct, indirect, incidental, consequential, or exemplary damages resulting from your use of the app or its services.</p>
                        </li>
                        <li>Changes to Terms
                            <p>We reserve the right to modify these Terms and Conditions at any time. You are responsible for reviewing these terms regularly to stay informed of any changes. Your continued use of the Love Calculator App after any modifications signifies your acceptance of the updated terms.</p>
                        </li>
                        <li>Termination
                            <p>We reserve the right to suspend or terminate your access to the Love Calculator App at any time for any reason, without notice.</p>
                        </li>
                        <li>Governing Law
                            <p>These Terms and Conditions shall be governed by and construed in accordance with the laws of Singapore, and you agree to submit to the exclusive jurisdiction of the [State] courts.</p> 
                        </li>
                        <li>Contact Us
                            <p>If you have any questions about these Terms and Conditions, please contact us at love-calculator@gmail.com.</p>
                        </li>
                        <li>
                            <p>By using the Love Calculator App, you acknowledge that you have read, understood, and agreed to these Terms and Conditions. Thank you for choosing our Love Calculator App – we hope you enjoy using it!

                            Last updated: [Date]

                            Please note that the above Terms and Conditions are provided as a template and should be reviewed by a legal professional to ensure they meet the specific legal requirements and regulations of your jurisdiction and the nature of your app.</p>
                        </li>
                    </ol>   
                </p>
                <button className="btn btn-outline-info w-25 align-self-center mb-3" onClick={ handleBack }>BACK</button>
            </div>
            <div className="d-flex align-items-center justify-content-center w-100 bg-dark border border-dark rounded-3 m-0 py-2">
                <h5 className="text-light fs-6">&copy;Love Calculator 2023</h5>
            </div>
        </div>
    );
}

// export component
export default Terms;